import 'dart:io';

/// Test fixtures are read from disk rather than embedded, so the PEMs stay
/// readable and can be regenerated by the cross-check procedure.
String loadFixture(String name) =>
    File('test/fixtures/$name').readAsStringSync();
